name: Build and Publish to npm

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the build and tests
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      # Installs dependencies
      - name: Install dependencies
        run: npm install

      # Runs the linter
      - name: Lint project
        run: npm run lint

      # Runs the tests
      - name: Test project
        run: npm test

      # Runs the build script
      - name: Build package
        run: npm run build

  # This job publishes the package to npm
  publish:
    # This job only runs when the workflow is manually dispatched
    if: github.event_name == 'workflow_dispatch'
    # It depends on the 'build' job to succeed
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      # The prepublishOnly script will run the build automatically before publishing
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
